github:
  api_token: '%env(GITHUB_API_TOKEN)%'
  repository: famoser/agnes

servers:
  mangel.io:
    host: '%env(SERVER_HOST)%'
    user: '%env(SERVER_USER)%'
    path: '%env(SERVER_PATH)%' # the path of the installation will be $path/$environment_name/$environment
    keep_releases: 2
    environments:
      app.mangel.io: [production, education, staging, dev]

policies:
  strategy: unanimous # all matching policies must be valid
  allow_if_all_abstain: true # if no matching policy is found, the execution is allowed

  deploy:
    - type: write_up
      filter: null
      layers:
        0: [production, education]
        1: [staging]
        2: [dev]

    - type: branch_whitelist
      filter:
        environment: [production, education, staging]
      branch: [master]

  copy_shared:
    - type: write_down
      filter: null
      layers:
        0: [production]
        1: [dev, staging, education]

  fixtures:
    - type: whitelist
      filter:
        environment: [dev]

events:
  deploy:
    before:
      - filter:
          environment: [staging]
        command: copy_shared
        arguments: { source: production }

    after:
      - filter:
          environment: [dev]
        command: fixtures
