release_adapter: github

policies:
  strategy: unanimous # all matching policies must be valid
  allow_if_all_abstain: true # if no matching policy is found, the execution is allowed

  deploy:
    - type: write_up
      filter: null
      layers:
        0: [production, education]
        1: [staging]
        2: [dev]
        
    - type: branch_whitelist
      filter:
        environment: [production, education, staging]
      branch: [master]

  copy_shared:
    - type: write_down
      filter: null
      layers:
        0: [production]
        1: [dev, staging, education]

  fixtures:
    - type: whitelist
      filter:
        environment: [dev]


events:
  deploy:
    before:
      - filter:
          environment: [staging]
        command: copy_shared
        arguments: { source: production }

    after:
      - filter:
          environment: [dev]
        command: fixtures
