release:
  adapter: github

deploy:
  policies:
    - type: write_up
      filter: null
      layers:
        0: [production, education]
        1: [staging]
        2: [dev]
    - type: branch_whitelist
      filter:
        environment: [production, education, staging]
      branch: [master]

  before:
    - filter:
        environment: [staging]
      command: copy_shared
      arguments: { source: production }

  after:
    - filter:
        environment: [dev]
      command: fixtures

rollback:

copy_shared:
  policies:
    - type: write_down
      filter: null
      layers:
        0: [production]
        1: [dev, staging, education]

fixtures:
  whitelist: [dev]
