deploy:
  groups:
    1: [production, education]
    2: [staging]
    3: [dev]
  directions:
    up: true
    cross: true
    down: false

copy_shared:
  groups:
    1: [production]
    2: [dev, staging, education]
  directions:
    up: false
    cross: true
    down: true

fixtures:
  groups:
    1: [dev]